USE LogisTruck;

-- 1. CLIENTES
ALTER TABLE clientes_b2b
ADD COLUMN data_criacao TIMESTAMP
NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- 2. MOTORISTAS
ALTER TABLE motoristas
ADD COLUMN status_ativo BOOLEAN
NOT NULL DEFAULT TRUE;

-- 3. CAMINHOES
ALTER TABLE caminhoes
ADD COLUMN usuario_ultima_alteracao VARCHAR(80);

-- 4. ROTAS
ALTER TABLE rotas
ADD COLUMN status_ativa BOOLEAN
NOT NULL DEFAULT TRUE;

-- 5. ENTREGAS
ALTER TABLE entregas
ADD COLUMN observacoes_internas VARCHAR(255);

-- 6. MANUTENCOES
ALTER TABLE manutencoes
ADD COLUMN data_registro TIMESTAMP
NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- 7. ABASTECIMENTOS
ALTER TABLE abastecimentos
ADD COLUMN data_registro TIMESTAMP
NOT NULL DEFAULT CURRENT_TIMESTAMP;